import TerraButton from '@nasa-terra/components/dist/react/button/index.js'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>
                    <p>
                        Get started by editing&nbsp;
                        <code>pages/index.tsx</code>
                    </p>
                </div>

                <div>
                    <h1>Terra UI Components</h1>
                </div>

                <div>
                    <TerraButton variant="default">Default</TerraButton>
                    <TerraButton variant="primary">Primary</TerraButton>
                    <TerraButton variant="success">Success</TerraButton>
                    <TerraButton variant="warning">Warning</TerraButton>
                    <TerraButton variant="danger">Danger</TerraButton>
                </div>
            </main>
        </>
    )
}
